env:
  browser: true
  jquery: true
extends:
  - eslint:recommended
  - standard
  - standard-react
installedESLint: true
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - babel
  - react
rules:
  indent:
    - error
    - 2
  react/prop-types: 0
  semi :
    - 2
    - always
  react/jsx-no-bind:
    - 1
    - allowArrowFunctions: true
  object-curly-spacing:
    - 2
    - never
  key-spacing:
    - 2
    - align: value
  camelcase:
    - error
    - properties: never
  generator-star-spacing: 0
  babel/generator-star-spacing: 1
globals:
  __DEV__      : false
  __PROD__     : false
  __DEBUG__    : false
  __COVERAGE__ : false
  __BASENAME__ : false
