import './palette.js';
import './ui-jp.js';
import './ui-include.js';
import './ui-device.js';
import './ui-form.js';
import './ui-nav.js';
import './ui-toggle-class.js';
import './app.js';
import './ajax.js';
