// +++""ADMIN""+++

// 'INVENTORY'

export const ACTION_SUCCESS_ADD_NEW_MACHINE = 'ACTION_SUCCESS_ADD_NEW_MACHINE'
export const ACTION_ERROR_ADD_NEW_MACHINE = 'ACTION_ERROR_ADD_NEW_MACHINE'
// Get DEvice List
export const ACTION_SUCCESS_DEVICE_LIST = 'ACTION_SUCCESS_DEVICE_LIST'
export const ACTION_EMPTY_DEVICE_LIST = 'ACTION_EMPTY_DEVICE_LIST'
export const ACTION_ERROR_DEVICE_LIST = 'ACTION_ERROR_DEVICE_LIST'
export const ACTION_SUCCESS_GET_DEVICELIST = 'ACTION_SUCCESS_GET_DEVICELIST'
// Update DEvice List
export const ACTION_SUCCESS_UPDATE_DEVICELIST = 'ACTION_SUCCESS_UPDATE_DEVICELIST'
// Delete Device List
export const ACTION_SUCCESS_DELETE_DEVICELIST = 'ACTION_SUCCESS_DELETE_DEVICELIST'
// Assign Device
export const ACTION_SUCCESS_ASSIGN_DEVICE = 'ACTION_SUCCESS_ASSIGN_DEVICE'
export const ACTION_ERROR_ASSIGN_DEVICE = 'ACTION_ERROR_ASSIGN_DEVICE'
// Device Type
export const ACTION_SUCCESS_DEVICE_TYPE = 'ACTION_SUCCESS_DEVICE_TYPE'
export const ACTION_ERROR_DEVICE_TYPE = 'ACTION_ERROR_DEVICE_TYPE'
// Device Type List
export const ACTION_SUCCESS_GET_DEVICE_TYPE_LIST = 'ACTION_SUCCESS_GET_DEVICE_TYPE_LIST'
// DEvice Status
export const ACTION_SUCCESS_DEVICE_STATUS = 'ACTION_SUCCESS_DEVICE_STATUS'
export const ACTION_ERROR_DEVICE_STATUS = 'ACTION_ERROR_DEVICE_STATUS'
export const ACTION_SUCCESS_GET_DEVICE_STATUS_LIST = 'ACTION_SUCCESS_GET_DEVICE_STATUS_LIST'
export const ACTION_SUCCESS_DELETE_DEVICE_STATUS_LIST = 'ACTION_SUCCESS_DELETE_DEVICE_STATUS_LIST'
export const ACTION_SUCCESS_DEVICE_COUNT = 'ACTION_SUCCESS_DEVICE_COUNT'
// LEAVE SUMMARY

export const ACTION_SUCCESS_LEAVES_SUMMARY = 'ACTION_SUCCESS_LEAVES_SUMMARY'
export const ACTION_EMPTY_LEAVES_SUMMARY = 'ACTION_EMPTY_LEAVES_SUMMARY'
export const ACTION_ERROR_LEAVES_SUMMARY = 'ACTION_ERROR_LEAVES_SUMMARY'

// MANAGE CLIENTS
export const ACTION_SUCCESS_CLIENT_DETAILS = 'ACTION_SUCCESS_CLIENT_DETAILS'
export const ACTION_EMPTY_CLIENT_DETAILS = 'ACTION_EMPTY_CLIENT_DETAILS'
export const ACTION_ERROR_CLIENT_DETAILS = 'ACTION_ERROR_CLIENT_DETAILS'
// Add a new client
export const ACTION_SUCCESS_ADD_NEW_CLIENT = 'ACTION_SUCCESS_ADD_NEW_CLIENT'
export const ACTION_ERROR_ADD_NEW_CLIENT = 'ACTION_ERROR_ADD_NEW_CLIENT'
// Update Client Info
export const ACTION_SUCCESS_UPDATE_CLIENT_DETAILS = 'ACTION_SUCCESS_UPDATE_CLIENT_DETAILS'
export const ACTION_ERROR_UPDATE_CLIENT_DETAILS = 'ACTION_ERROR_UPDATE_CLIENT_DETAILS'
// /-----create client new invoice
export const ACTION_SUCCESS_CREATE_CLIENT_INVOICE = 'ACTION_SUCCESS_CREATE_CLIENT_INVOICE'
export const ACTION_ERROR_CREATE_CLIENT_INVOICE = 'ACTION_ERROR_CREATE_CLIENT_INVOICE'
// /-----delete invoice
export const ACTION_SUCCESS_INVOICE_DELETE = 'ACTION_SUCCESS_INVOICE_DELETE'
export const ACTION_ERROR_INVOICE_DELETE = 'ACTION_ERROR_INVOICE_DELETE'

// MANAGE PAYSLIPS

export const ACTION_SUCCESS_USER_MANAGE_PAYSLIPS_DATA = 'ACTION_SUCCESS_USER_MANAGE_PAYSLIPS_DATA'
export const ACTION_ERROR_USER_MANAGE_PAYSLIPS_DATA = 'ACTION_ERROR_USER_MANAGE_PAYSLIPS_DATA'
// export const ACTION_SUCCESS_TEAM_LIST = 'ACTION_SUCCESS_TEAM_LIST'
// export const ACTION_EMPTY_TEAM_LIST = 'ACTION_EMPTY_TEAM_LIST'
// export const ACTION_ERROR_TEAM_LIST = 'ACTION_ERROR_TEAM_LIST'

// create user payslip
export const ACTION_SUCCESS_CREATE_USER_SALARY_SLIP = 'ACTION_SUCCESS_CREATE_USER_SALARY_SLIP'
export const ACTION_ERROR_CREATE_USER_SALARY_SLIP = 'ACTION_ERROR_CREATE_USER_SALARY_SLIP'
// ------email payslips
export const ACTION_SUCCESS_EMAIL_PAYSLIPS = 'ACTION_SUCCESS_EMAIL_PAYSLIPS'
export const ACTION_ERROR_EMAIL_PAYSLIPS = 'ACTION_ERROR_EMAIL_PAYSLIPS'
// ------save google access token
export const ACTION_SUCCESS_SAVE_GOOGLE_ACCESS_TOKEN = 'ACTION_SUCCESS_SAVE_GOOGLE_ACCESS_TOKEN'
export const ACTION_ERROR_SAVE_GOOGLE_ACCESS_TOKEN = 'ACTION_ERROR_SAVE_GOOGLE_ACCESS_TOKEN'

// MANAGE SALARY
export const ACTION_SUCCESS_USER_SALARY_DETAILS = 'ACTION_SUCCESS_USER_SALARY_DETAILS'
export const ACTION_EMPTY_USER_SALARY_DETAILS = 'ACTION_EMPTY_USER_SALARY_DETAILS'

export const ACTION_SUCCESS_ADD_USER_SALARY = 'ACTION_SUCCESS_ADD_USER_SALARY'
export const ACTION_ERROR_ADD_USER_SALARY = 'ACTION_ERROR_ADD_USER_SALARY'

// holding
export const ACTION_SUCCESS_ADD_USER_HOLDING = 'ACTION_SUCCESS_ADD_USER_HOLDING'
export const ACTION_ERROR_ADD_USER_HOLDING = 'ACTION_ERROR_ADD_USER_HOLDING'

export const ACTION_SUCCESS_DELETE_USER_SALARY = 'ACTION_SUCCESS_DELETE_USER_SALARY'
export const ACTION_ERROR_DELETE_USER_SALARY = 'ACTION_ERROR_DELETE_USER_SALARY'

// MANAGE USERS

export const ACTION_SUCCESS_USER_PROFILE = 'ACTION_SUCCESS_USER_PROFILE'
export const ACTION_EMPTY_USER_PROFILE = 'ACTION_EMPTY_USER_PROFILE'
export const ACTION_ERROR_USER_PROFILE = 'ACTION_ERROR_USER_PROFILE'

// MANAGE ROLES
export const ACTION_SUCCESS_ADD_ROLE = 'ACTION_SUCCESS_ADD_ROLE'
export const ACTION_ERROR_ADD_ROLE = 'ACTION_ERROR_ADD_ROLE'

export const ACTION_SUCCESS_LIST_ROLES = 'ACTION_SUCCESS_LIST_ROLES'
export const ACTION_EMPTY_LIST_ROLES = 'ACTION_EMPTY_LIST_ROLES'
export const ACTION_ERROR_LIST_ROLES = 'ACTION_ERROR_LIST_ROLES'

export const ACTION_SUCCESS_UPDATE_ROLES = 'ACTION_SUCCESS_UPDATE_ROLES'
export const ACTION_ERROR_UPDATE_ROLES = 'ACTION_ERROR_UPDATE_ROLES'

// -------update profile details
export const ACTION_SUCCESS_UPDATE_USER_PROFILE_DETAILS = 'ACTION_SUCCESS_UPDATE_USER_PROFILE_DETAILS'
export const ACTION_ERROR_UPDATE_USER_PROFILE_DETAILS = 'ACTION_ERROR_UPDATE_USER_PROFILE_DETAILS'
// -------add New employee
export const ACTION_SUCCESS_ADD_NEW_EMPLOYEE = 'ACTION_SUCCESS_ADD_NEW_EMPLOYEE'
export const ACTION_ERROR_ADD_NEW_EMPLOYEE = 'ACTION_ERROR_ADD_NEW_EMPLOYEE'
// user documents
export const ACTION_SUCCESS_USER_DOCUMENT = 'ACTION_SUCCESS_USER_DOCUMENT'
export const ACTION_ERROR_USER_DOCUMENT = 'ACTION_SUCCESS_USER_DOCUMENT'

// MANAGE USER WORKING HOURS

export const ACTION_SUCCESS_USER_WORKING_HOURS = 'ACTION_SUCCESS_USER_WORKING_HOURS'
export const ACTION_EMPTY_USER_WORKING_HOURS = 'ACTION_EMPTY_USER_WORKING_HOURS'
export const ACTION_ERROR_USER_WORKING_HOURS = 'ACTION_ERROR_USER_WORKING_HOURS'

export const ACTION_SUCCESS_ADD_USER_WORKING_HOURS = 'ACTION_SUCCESS_ADD_USER_WORKING_HOURS'
export const ACTION_ERROR_ADD_USER_WORKING_HOURS = 'ACTION_ERROR_ADD_USER_WORKING_HOURS'

// TEAM LIST

export const ACTION_SUCCESS_ADD_TEAM = 'ACTION_SUCCESS_ADD_TEAM'
export const ACTION_ERROR_ADD_TEAM = 'ACTION_ERROR_ADD_TEAM'
export const ACTION_SUCCESS_TEAM_LIST = 'ACTION_SUCCESS_TEAM_LIST'
export const ACTION_EMPTY_TEAM_LIST = 'ACTION_EMPTY_TEAM_LIST'
export const ACTION_ERROR_TEAM_LIST = 'ACTION_ERROR_TEAM_LIST'
export const ACTION_SUCCESS_GET_TEAM_CANDIDATE = 'ACTION_SUCCESS_GET_TEAM_CANDIDATE'
export const ACTION_ERROR_GET_TEAM_CANDIDATE = 'ACTION_ERROR_GET_TEAM_CANDIDATE'

// TEMAPLATES

export const ACTION_SUCCESS_GET_TEMPLATES = 'ACTION_SUCCESS_GET_TEMPLATES'
export const ACTION_SUCCESS_ADD_VARIABLE = 'ACTION_SUCCESS_ADD_VARIABLE'
export const ACTION_ERROR_ADD_VARIABLE = 'ACTION_ERROR_ADD_VARIABLE'
export const ACTION_SUCCESS_VARIABLE_GET = 'ACTION_SUCCESS_VARIABLE_GET'
// export const ACTION_UPDATE_PROGRESS_STATUS = "ACTION_UPDATE_PROGRESS_STATUS"
// export const UPDATE_TAGID = "UPDATE_TAGID"

// WORKING HOURS SUMMARY

export const ACTION_SUCCESS_HOURS_SUMMARY = 'ACTION_SUCCESS_HOURS_SUMMARY'
export const ACTION_EMPTY_HOURS_SUMMARY = 'ACTION_EMPTY_HOURS_SUMMARY'
export const ACTION_ERROR_HOURS_SUMMARY = 'ACTION_ERROR_HOURS_SUMMARY'
// Update day working time
export const ACTION_EMPTY_UPDATE_HOURS_SUMMARY = 'ACTION_EMPTY_UPDATE_HOURS_SUMMARY'
export const ACTION_ERROR_UPDATE_HOURS_SUMMARY = 'ACTION_ERROR_UPDATE_HOURS_SUMMARY'

// +++GENERIC+++

// ClientList

export const ACTION_SUCCESS_CLIENTS_LIST = 'ACTION_SUCCESS_CLIENTS_LIST'
export const ACTION_EMPTY_CLIENTS_LIST = 'ACTION_EMPTY_CLIENTS_LIST'
export const ACTION_ERROR_CLIENTS_LIST = 'ACTION_ERROR_CLIENTS_LIST'
// front end

export const ACTION_SHOW_LOADING = 'ACTION_SHOW_LOADING'
export const ACTION_HIDE_LOADING = 'ACTION_HIDE_LOADING'

// +++LEAVE+++

// Apply Leave

export const ACTION_LEAVE_SUCCESS = 'ACTION_LEAVE_SUCCESS'
export const ACTION_LEAVE_FAIL = 'ACTION_LEAVE_FAIL'
export const ACTION_LEAVE_ERROR = 'ACTION_LEAVE_ERROR'
// get days between leaves

export const ACTION_DAYS_BETWEEN_LEAVES_SUCCESS = 'ACTION_DAYS_BETWEEN_LEAVES_SUCCESS'
export const ACTION_DAYS_BETWEEN_LEAVES_FAIL = 'ACTION_DAYS_BETWEEN_LEAVES_FAIL'
export const ACTION_DAYS_BETWEEN_LEAVES_ERROR = 'ACTION_DAYS_BETWEEN_LEAVES_ERROR'

// LIST LEAVES
export const ACTION_LIST_LEAVES_SUCCESS = 'ACTION_LIST_LEAVES_SUCCESS'
export const ACTION_LIST_LEAVES_EMPTY = 'ACTION_LIST_LEAVES_EMPTY'
export const ACTION_LIST_LEAVES_ERROR = 'ACTION_LIST_LEAVES_ERROR'

// Filter leaves
export const ACTION_SELECT_LEAVE = 'ACTION_SELECT_LEAVE'
export const ACTION_LEAVE_FILTER = 'ACTION_LEAVE_FILTER'

// MANAGE LEAVES
export const ACTION_LEAVE_STATUS_CHANGE_SUCCESS = 'ACTION_LEAVE_STATUS_CHANGE_SUCCESS'
export const ACTION_LEAVE_STATUS_CHANGE_FAIL = 'ACTION_LEAVE_STATUS_CHANGE_FAIL'
export const ACTION_LEAVE_STATUS_CHANGE_ERROR = 'ACTION_LEAVE_STATUS_CHANGE_ERROR'
// my leaves

export const ACTION_LIST_MY_LEAVES_SUCCESS = 'ACTION_LIST_MY_LEAVES_SUCCESS'
export const ACTION_LIST_MY_LEAVES_EMPTY = 'ACTION_LIST_MY_LEAVES_EMPTY'
export const ACTION_LIST_MY_LEAVES_ERROR = 'ACTION_LIST_MY_LEAVES_ERROR'

 // +++LOGIN+++

export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS'
export const ACTION_LOGIN_FAIL = 'ACTION_LOGIN_FAIL'
export const ACTION_LOGIN_ERROR = 'ACTION_LOGIN_ERROR'
// logout
export const ACTION_LOGOUT = 'ACTION_LOGOUT'
// forgot password
export const ACTION_SUCCESS_FORGOT_PASSWORD = 'ACTION_SUCCESS_FORGOT_PASSWORD'
export const ACTION_ERROR_FORGOT_PASSWORD = 'ACTION_ERROR_FORGOT_PASSWORD'

// +++policy documents+++

export const ACTION_POLICY_DOCUMENT_SUCCESS = 'ACTION_POLICY_DOCUMENT_SUCCESS'
export const ACTION_POLICY_DOCUMENT_FAIL = 'ACTION_POLICY_DOCUMENT_FAIL'
// export const ACTION_LOGIN_ERROR = "ACTION_LOGIN_ERROR"

// +++SALARY+++

export const ACTION_SUCCESS_SALARY_DETAILS = 'ACTION_SUCCESS_SALARY_DETAILS'
export const ACTION_EMPTY_SALARY_DETAILS = 'ACTION_EMPTY_SALARY_DETAILS'
export const ACTION_ERROR_USER_SALARY_DETAILS = 'ACTION_ERROR_USER_SALARY_DETAILS'

// +++USER+++

// attendence SUMMARY
export const ACTION_SUCCESS_ATTENDANCE_SUMMARY = 'ACTION_SUCCESS_ATTENDANCE_SUMMARY'
export const ACTION_EMPTY_ATTENDANCE_SUMMARY = 'ACTION_EMPTY_ATTENDANCE_SUMMARY'
export const ACTION_ERROR_ATTENDANCE_SUMMARY = 'ACTION_ERROR_ATTENDANCE_SUMMARY'
// holiday list

export const ACTION_SUCCESS_HOLIDAYSLIST = 'ACTION_SUCCESS_HOLIDAYSLIST'
export const ACTION_EMPTY_HOLIDAYSLIST = 'ACTION_EMPTY_HOLIDAYSLIST'
export const ACTION_ERROR_HOLIDAYSLIST = 'ACTION_ERROR_HOLIDAYSLIST'
// monthly attendence
export const ACTION_SUCCESS_USER_ATTENDANCE = 'ACTION_SUCCESS_USER_ATTENDANCE'
export const ACTION_EMPTY_USER_ATTENDANCE = 'ACTION_EMPTY_USER_ATTENDANCE'
export const ACTION_ERROR_USER_ATTENDANCE = 'ACTION_ERROR_USER_ATTENDANCE'

// my document
export const ACTION_SUCCESS_MY_DOCUMENT = 'ACTION_SUCCESS_MY_DOCUMENT'
export const ACTION_ERROR_MY_DOCUMENT = 'ACTION_ERROR_MY_DOCUMENT'
// my profile
export const ACTION_SUCCESS_MY_PROFILE = 'ACTION_SUCCESS_MY_PROFILE'
export const ACTION_EMPTY_MY_PROFILE = 'ACTION_EMPTY_MY_PROFILE'
export const ACTION_ERROR_MY_PROFILE = 'ACTION_ERROR_MY_PROFILE'
// update profile details
export const ACTION_SUCCESS_UPDATE_PROFILE_DETAILS = 'ACTION_SUCCESS_UPDATE_PROFILE_DETAILS'
export const ACTION_ERROR_UPDATE_PROFILE_DETAILS = 'ACTION_ERROR_UPDATE_PROFILE_DETAILS'
// update bank details
export const ACTION_SUCCESS_UPDATE_BANK_DETAILS = 'ACTION_SUCCESS_UPDATE_BANK_DETAILS'
export const ACTION_ERROR_UPDATE_BANK_DETAILS = 'ACTION_ERROR_UPDATE_BANK_DETAILS'
// update password
export const ACTION_SUCCESS_UPDATE_PASSWORD = 'ACTION_SUCCESS_UPDATE_PASSWORD'
export const ACTION_ERROR_UPDATE_PASSWORD = 'ACTION_ERROR_UPDATE_PASSWORD'
// get user day summary
export const ACTION_SUCCESS_USER_DAY_SUMMARY = 'ACTION_SUCCESS_USER_DAY_SUMMARY'
export const ACTION_ERROR_USER_DAY_SUMMARY = 'ACTION_ERROR_USER_DAY_SUMMARY'
export const ACTION_EMPTY_USER_DAY_SUMMARY = 'ACTION_EMPTY_USER_DAY_SUMMARY'

// ///update user day summary
export const ACTION_SUCCESS_UPDATE_USER_DAY_SUMMARY = 'ACTION_SUCCESS_UPDATE_USER_DAY_SUMMARY'
export const ACTION_ERROR_UPDATE_USER_DAY_SUMMARY = 'ACTION_ERROR_UPDATE_USER_DAY_SUMMARY'
export const ACTION_EMPTY_UPDATE_USER_DAY_SUMMARY = 'ACTION_EMPTY_UPDATE_USER_DAY_SUMMARY'

// USERS LIST

export const ACTION_SUCCESS_USERSLIST = 'ACTION_SUCCESS_USERSLIST'
export const ACTION_EMPTY_USERSLIST = 'ACTION_EMPTY_USERSLIST'
export const ACTION_ERROR_USERSLIST = 'ACTION_ERROR_USERSLIST'
export const ACTION_SUCCESS_DISABLED_USERSLIST = 'ACTION_SUCCESS_DISABLED_USERSLIST'
export const ACTION_ERROR_DISABLED_USERSLIST = 'ACTION_ERROR_DISABLED_USERSLIST'
