// +++LOGIN+++
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'ACTION_LOGIN_FAIL';
export const USER_LOGIN_ERROR = 'ACTION_LOGIN_ERROR';
export const IS_ALREADY_LOGGED_IN = 'IS_ALREADY_LOGGED_IN';

// logout
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// forgot password
export const REQUEST_FORGOT_PASSWORD = 'REQUEST_FORGOT_PASSWORD';
export const SUCCESS_FORGOT_PASSWORD = 'SUCCESS_FORGOT_PASSWORD';
export const ERROR_FORGOT_PASSWORD = 'ERROR_FORGOT_PASSWORD';

// holiday list
export const REQUEST_HOLIDAYSLIST = 'REQUEST_HOLIDAYSLIST';
export const SUCCESS_HOLIDAYSLIST = 'SUCCESS_HOLIDAYSLIST';
export const ERROR_HOLIDAYSLIST = 'ERROR_HOLIDAYSLIST';

// monthly attendence
export const REQUEST_USER_ATTENDANCE = 'REQUEST_USER_ATTENDANCE';
export const SUCCESS_USER_ATTENDANCE = 'ACTION_SUCCESS_USER_ATTENDANCE';
export const ERROR_USER_ATTENDANCE = 'ACTION_ERROR_USER_ATTENDANCE';

// attendence REQUEST
export const REQUEST_USER_ATTENDANCE_REQUEST = 'REQUEST_USER_ATTENDANCE_REQUEST';
export const SUCCESS_USER_ATTENDANCE_REQUEST = 'ACTION_SUCCESS_USER_ATTENDANCE_REQUEST';
export const ERROR_USER_ATTENDANCE_REQUEST = 'ACTION_ERROR_USER_ATTENDANCE_REQUEST';
// attendence status
export const REQUEST_USER_ATTENDANCE_STATUS = 'REQUEST_USER_ATTENDANCE_STATUS';
export const SUCCESS_USER_ATTENDANCE_STATUS = 'ACTION_SUCCESS_USER_ATTENDANCE_STATUS';
export const ERROR_USER_ATTENDANCE_STATUS = 'ACTION_ERROR_USER_ATTENDANCE_STATUS';

// get user day summary
export const REQUEST_USER_DAY_SUMMARY = 'REQUEST_USER_DAY_SUMMARY';
export const SUCCESS_USER_DAY_SUMMARY = 'ACTION_SUCCESS_USER_DAY_SUMMARY';
export const ERROR_USER_DAY_SUMMARY = 'ACTION_ERROR_USER_DAY_SUMMARY';

// update user day summary
export const REQUEST_UPDATE_USER_DAY_SUMMARY = 'REQUEST_UPDATE_USER_DAY_SUMMARY';
export const SUCCESS_UPDATE_USER_DAY_SUMMARY = 'ACTION_SUCCESS_UPDATE_USER_DAY_SUMMARY';
export const ERROR_UPDATE_USER_DAY_SUMMARY = 'ACTION_ERROR_UPDATE_USER_DAY_SUMMARY';

// user update day summary --
export const REQUEST_UPDATE_EMP_DAY_SUMMARY = 'REQUEST_UPDATE_EMP_DAY_SUMMARY';
export const SUCCESS_UPDATE_EMP_DAY_SUMMARY = 'ACTION_SUCCESS_UPDATE_EMP_DAY_SUMMARY';
export const ERROR_UPDATE_EMP_DAY_SUMMARY = 'ACTION_ERROR_UPDATE_EMP_DAY_SUMMARY';
// USERS LIST
export const REQUEST_USERSLIST = 'ACTION_EMPTY_USERSLIST';
export const SUCCESS_USERSLIST = 'ACTION_SUCCESS_USERSLIST';
export const ERROR_USERSLIST = 'ACTION_ERROR_USERSLIST';

// POLICY DOCUMENTS
export const REQUEST_POLICY_DOCUMENT = 'REQUEST_POLICY_DOCUMENT';

export const REQUEST_USER_POLICY_DOCUMENT = 'REQUEST_USER_POLICY_DOCUMENT';
export const SUCCESS_POLICY_DOCUMENT = 'SUCCESS_POLICY_DOCUMENT';
export const ERROR_POLICY_DOCUMENT = 'ERROR_POLICY_DOCUMENT';

export const REQUEST_SUBMIT_DOCS = 'REQUEST_SUBMIT_DOCS';
export const SUCCESS_SUBMIT_DOCS = 'SUCCESS_SUBMIT_DOCS';
export const ERROR_SUBMIT_DOCS = 'ERROR_SUBMIT_DOCS';

export const REQUEST_UPDATE_READ = 'REQUEST_UPDATE_READ';
export const SUCCESS_UPDATE_READ = 'SUCCESS_UPDATE_READ';
export const ERROR_UPDATE_READ = 'ERROR_UPDATE_READ';

// TEAM LIST
export const REQUEST_TEAM_LIST = 'REQUEST_TEAM_LIST';
export const SUCCESS_TEAM_LIST = 'SUCCESS_TEAM_LIST';
export const ERROR_TEAM_LIST = 'ERROR_TEAM_LIST';

export const REQUEST_ADD_TEAM = 'REQUEST_ADD_TEAM';
export const SUCCESS_ADD_TEAM = 'SUCCESS_ADD_TEAM';
export const ERROR_ADD_TEAM = 'ERROR_ADD_TEAM';

export const REQUEST_GET_TEAM = 'REQUEST_GET_TEAM';
export const SUCCESS_GET_TEAM = 'SUCCESS_GET_TEAM';
export const ERROR_GET_TEAM = 'ERROR_GET_TEAM';

export const REQUEST_TEAM_STATS = 'REQUEST_TEAM_STATS';
export const SUCCESS_TEAM_STATS = 'SUCCESS_TEAM_STATS';
export const ERROR_TEAM_STATS = 'ERROR_TEAM_STATS';

export const REQUEST_EMP_LIFE_CYCLE = 'REQUEST_EMP_LIFE_CYCLE';
export const SUCCESS_EMP_LIFE_CYCLE = 'SUCCESS_EMP_LIFE_CYCLE';
export const ERROR_EMP_LIFE_CYCLE = 'ERROR_EMP_LIFE_CYCLE';

export const REQUEST_EMP_HOURS = 'REQUEST_EMP_HOURS';
export const SUCCESS_EMP_HOURS = 'SUCCESS_EMP_HOURS';
export const ERROR_EMP_HOURS = 'ERROR_EMP_HOURS';

export const REQUEST_EMP_MONTHLY_HOURS = 'REQUEST_EMP_MONTHLY_HOURS';
export const SUCCESS_EMP_MONTHLY_HOURS = 'SUCCESS_EMP_MONTHLY_HOURS';
export const ERROR_EMP_MONTHLY_HOURS = 'ERROR_EMP_MONTHLY_HOURS';

export const REQUEST_EMP_PERFORMANCE = 'REQUEST_EMP_PERFORMANCE';
export const SUCCESS_EMP_PERFORMANCE = 'SUCCESS_EMP_PERFORMANCE';
export const ERROR_EMP_PERFORMANCE = 'ERROR_EMP_PERFORMANCE';

//* **********************************************************************************
// +++""ADMIN""+++

export const ACTION_SUCCESS_DISABLED_USERSLIST = 'ACTION_SUCCESS_DISABLED_USERSLIST';
export const ACTION_ERROR_DISABLED_USERSLIST = 'ACTION_ERROR_DISABLED_USERSLIST';

// 'INVENTORY'
export const ACTION_SUCCESS_ADD_NEW_MACHINE = 'ACTION_SUCCESS_ADD_NEW_MACHINE';
export const ACTION_ERROR_ADD_NEW_MACHINE = 'ACTION_ERROR_ADD_NEW_MACHINE';

// Get DEvice List
export const ACTION_SUCCESS_DEVICE_LIST = 'ACTION_SUCCESS_DEVICE_LIST';
export const ACTION_EMPTY_DEVICE_LIST = 'ACTION_EMPTY_DEVICE_LIST';
export const ACTION_ERROR_DEVICE_LIST = 'ACTION_ERROR_DEVICE_LIST';
export const ACTION_SUCCESS_GET_DEVICELIST = 'ACTION_SUCCESS_GET_DEVICELIST';

// Update DEvice List
export const ACTION_SUCCESS_UPDATE_DEVICELIST = 'ACTION_SUCCESS_UPDATE_DEVICELIST';

// Delete Device List
export const ACTION_SUCCESS_DELETE_DEVICELIST = 'ACTION_SUCCESS_DELETE_DEVICELIST';

// Assign Device
export const ACTION_SUCCESS_ASSIGN_DEVICE = 'ACTION_SUCCESS_ASSIGN_DEVICE';
export const ACTION_ERROR_ASSIGN_DEVICE = 'ACTION_ERROR_ASSIGN_DEVICE';

// Device Type
export const ACTION_SUCCESS_DEVICE_TYPE = 'ACTION_SUCCESS_DEVICE_TYPE';
export const ACTION_ERROR_DEVICE_TYPE = 'ACTION_ERROR_DEVICE_TYPE';

// Device Type List
export const ACTION_SUCCESS_GET_DEVICE_TYPE_LIST = 'ACTION_SUCCESS_GET_DEVICE_TYPE_LIST';

// DEvice Status
export const ACTION_SUCCESS_DEVICE_STATUS = 'ACTION_SUCCESS_DEVICE_STATUS';
export const ACTION_ERROR_DEVICE_STATUS = 'ACTION_ERROR_DEVICE_STATUS';
export const ACTION_SUCCESS_GET_DEVICE_STATUS_LIST = 'ACTION_SUCCESS_GET_DEVICE_STATUS_LIST';
export const ACTION_SUCCESS_DELETE_DEVICE_STATUS_LIST = 'ACTION_SUCCESS_DELETE_DEVICE_STATUS_LIST';
export const ACTION_SUCCESS_DEVICE_COUNT = 'ACTION_SUCCESS_DEVICE_COUNT';

// LEAVE SUMMARY
export const ACTION_SUCCESS_LEAVES_SUMMARY = 'ACTION_SUCCESS_LEAVES_SUMMARY';
export const ACTION_EMPTY_LEAVES_SUMMARY = 'ACTION_EMPTY_LEAVES_SUMMARY';
export const ACTION_ERROR_LEAVES_SUMMARY = 'ACTION_ERROR_LEAVES_SUMMARY';

// MANAGE PAYSLIPS
export const ACTION_SUCCESS_USER_MANAGE_PAYSLIPS_DATA = 'ACTION_SUCCESS_USER_MANAGE_PAYSLIPS_DATA';
export const ACTION_ERROR_USER_MANAGE_PAYSLIPS_DATA = 'ACTION_ERROR_USER_MANAGE_PAYSLIPS_DATA';
// export const ACTION_SUCCESS_TEAM_LIST = 'ACTION_SUCCESS_TEAM_LIST'
// export const ACTION_EMPTY_TEAM_LIST = 'ACTION_EMPTY_TEAM_LIST'
// export const ACTION_ERROR_TEAM_LIST = 'ACTION_ERROR_TEAM_LIST'

// create user payslip
export const ACTION_SUCCESS_CREATE_USER_SALARY_SLIP = 'ACTION_SUCCESS_CREATE_USER_SALARY_SLIP';
export const ACTION_ERROR_CREATE_USER_SALARY_SLIP = 'ACTION_ERROR_CREATE_USER_SALARY_SLIP';
// ------email payslips
export const ACTION_SUCCESS_EMAIL_PAYSLIPS = 'ACTION_SUCCESS_EMAIL_PAYSLIPS';
export const ACTION_ERROR_EMAIL_PAYSLIPS = 'ACTION_ERROR_EMAIL_PAYSLIPS';
// ------save google access token
export const ACTION_SUCCESS_SAVE_GOOGLE_ACCESS_TOKEN = 'ACTION_SUCCESS_SAVE_GOOGLE_ACCESS_TOKEN';
export const ACTION_ERROR_SAVE_GOOGLE_ACCESS_TOKEN = 'ACTION_ERROR_SAVE_GOOGLE_ACCESS_TOKEN';

// MANAGE SALARY
export const ACTION_SUCCESS_USER_SALARY_DETAILS = 'ACTION_SUCCESS_USER_SALARY_DETAILS';
export const ACTION_EMPTY_USER_SALARY_DETAILS = 'ACTION_EMPTY_USER_SALARY_DETAILS';

export const ACTION_SUCCESS_ADD_USER_SALARY = 'ACTION_SUCCESS_ADD_USER_SALARY';
export const ACTION_ERROR_ADD_USER_SALARY = 'ACTION_ERROR_ADD_USER_SALARY';

// holding
export const ACTION_SUCCESS_ADD_USER_HOLDING = 'ACTION_SUCCESS_ADD_USER_HOLDING';
export const ACTION_ERROR_ADD_USER_HOLDING = 'ACTION_ERROR_ADD_USER_HOLDING';

export const ACTION_SUCCESS_DELETE_USER_SALARY = 'ACTION_SUCCESS_DELETE_USER_SALARY';
export const ACTION_ERROR_DELETE_USER_SALARY = 'ACTION_ERROR_DELETE_USER_SALARY';

// MANAGE USERS
export const ACTION_SUCCESS_USER_PROFILE = 'ACTION_SUCCESS_USER_PROFILE';
export const ACTION_EMPTY_USER_PROFILE = 'ACTION_EMPTY_USER_PROFILE';
export const ACTION_ERROR_USER_PROFILE = 'ACTION_ERROR_USER_PROFILE';

export const ACTION_SUCCESS_GET_STEPS = 'ACTION_SUCCESS_GET_STEPS';
export const ACTION_ERROR_GET_STEPS = 'ACTION_ERROR_GET_STEPS';

export const ACTION_SUCCESS_EMPLOYEE_STEPS = 'ACTION_SUCCESS_EMPLOYEE_STEPS';
export const ACTION_ERROR_EMPLOYEE_STEPS = 'ACTION_ERROR_EMPLOYEE_STEPS';

// MANAGE ROLES
export const ACTION_SUCCESS_ADD_ROLE = 'ACTION_SUCCESS_ADD_ROLE';
export const ACTION_ERROR_ADD_ROLE = 'ACTION_ERROR_ADD_ROLE';

export const ACTION_SUCCESS_LIST_ROLES = 'ACTION_SUCCESS_LIST_ROLES';
export const ACTION_EMPTY_LIST_ROLES = 'ACTION_EMPTY_LIST_ROLES';
export const ACTION_ERROR_LIST_ROLES = 'ACTION_ERROR_LIST_ROLES';

export const ACTION_SUCCESS_UPDATE_ROLES = 'ACTION_SUCCESS_UPDATE_ROLES';
export const ACTION_ERROR_UPDATE_ROLES = 'ACTION_ERROR_UPDATE_ROLES';

export const ACTION_SUCCESS_UPDATE_USER_ROLES = 'ACTION_SUCCESS_UPDATE_USER_ROLES';
export const ACTION_ERROR_UPDATE_USER_ROLES = 'ACTION_ERROR_UPDATE_USER_ROLES';

// -------update profile details
export const ACTION_SUCCESS_UPDATE_USER_PROFILE_DETAILS = 'ACTION_SUCCESS_UPDATE_USER_PROFILE_DETAILS';
export const ACTION_ERROR_UPDATE_USER_PROFILE_DETAILS = 'ACTION_ERROR_UPDATE_USER_PROFILE_DETAILS';
// -------add New employee
export const ACTION_SUCCESS_ADD_NEW_EMPLOYEE = 'ACTION_SUCCESS_ADD_NEW_EMPLOYEE';
export const ACTION_ERROR_ADD_NEW_EMPLOYEE = 'ACTION_ERROR_ADD_NEW_EMPLOYEE';
// user documents
export const ACTION_SUCCESS_USER_DOCUMENT = 'ACTION_SUCCESS_USER_DOCUMENT';
export const ACTION_ERROR_USER_DOCUMENT = 'ACTION_ERROR_USER_DOCUMENT';

// MANAGE USER WORKING HOURS

export const ACTION_SUCCESS_USER_WORKING_HOURS = 'ACTION_SUCCESS_USER_WORKING_HOURS';
export const ACTION_EMPTY_USER_WORKING_HOURS = 'ACTION_EMPTY_USER_WORKING_HOURS';
export const ACTION_ERROR_USER_WORKING_HOURS = 'ACTION_ERROR_USER_WORKING_HOURS';

export const ACTION_SUCCESS_ADD_USER_WORKING_HOURS = 'ACTION_SUCCESS_ADD_USER_WORKING_HOURS';
export const ACTION_ERROR_ADD_USER_WORKING_HOURS = 'ACTION_ERROR_ADD_USER_WORKING_HOURS';

// MANAGE USER Pending HOURS

export const ACTION_SUCCESS_USER_PENDING_HOURS = 'ACTION_SUCCESS_USER_PENDING_HOURS';
export const ACTION_EMPTY_USER_PENDING_HOURS = 'ACTION_EMPTY_USER_PENDING_HOURS';
export const ACTION_ERROR_USER_PENDING_HOURS = 'ACTION_ERROR_USER_PENDING_HOURS';

export const ACTION_SUCCESS_ADD_USER_PENDING_HOURS = 'ACTION_SUCCESS_ADD_USER_PENDING_HOURS';
export const ACTION_ERROR_ADD_USER_PENDING_HOURS = 'ACTION_ERROR_ADD_USER_PENDING_HOURS';

// pENDING hOUR lEAVE
export const ACTION_PENDING_LEAVE_SUCCESS = 'ACTION_PENDING_LEAVE_SUCCESS';
export const ACTION_PENDING_LEAVE_FAIL = 'ACTION_PENDING_LEAVE_FAIL';
export const ACTION_PENDING_LEAVE_ERROR = ' ACTION_PENDING_LEAVE_ERROR';
// get days between leaves

export const ACTION_DAYS_BETWEEN_PENDING_LEAVES_SUCCESS = 'ACTION_DAYS_BETWEEN_PENDING_LEAVES_SUCCESS';
export const ACTION_DAYS_BETWEEN_PENDING_LEAVES_FAIL = 'ACTION_DAYS_BETWEEN_PENDING_LEAVES_FAIL';
export const ACTION_DAYS_BETWEEN_PENDING_LEAVES_ERROR = 'ACTION_DAYS_BETWEEN_PENDING_LEAVES_ERROR';

// TEMAPLATES

export const ACTION_SUCCESS_GET_TEMPLATES = 'ACTION_SUCCESS_GET_TEMPLATES';
export const ACTION_SUCCESS_ADD_VARIABLE = 'ACTION_SUCCESS_ADD_VARIABLE';
export const ACTION_ERROR_ADD_VARIABLE = 'ACTION_ERROR_ADD_VARIABLE';
export const ACTION_SUCCESS_VARIABLE_GET = 'ACTION_SUCCESS_VARIABLE_GET';
// export const ACTION_UPDATE_PROGRESS_STATUS = "ACTION_UPDATE_PROGRESS_STATUS"
// export const UPDATE_TAGID = "UPDATE_TAGID"

// WORKING HOURS SUMMARY

export const ACTION_SUCCESS_HOURS_SUMMARY = 'ACTION_SUCCESS_HOURS_SUMMARY';
export const ACTION_EMPTY_HOURS_SUMMARY = 'ACTION_EMPTY_HOURS_SUMMARY';
export const ACTION_ERROR_HOURS_SUMMARY = 'ACTION_ERROR_HOURS_SUMMARY';
// Update day working time
export const ACTION_EMPTY_UPDATE_HOURS_SUMMARY = 'ACTION_EMPTY_UPDATE_HOURS_SUMMARY';
export const ACTION_ERROR_UPDATE_HOURS_SUMMARY = 'ACTION_ERROR_UPDATE_HOURS_SUMMARY';

// +++GENERIC+++

// front end

export const ACTION_SHOW_LOADING = 'ACTION_SHOW_LOADING';
export const ACTION_HIDE_LOADING = 'ACTION_HIDE_LOADING';

// +++LEAVE+++

// Apply Leave

export const ACTION_LEAVE_SUCCESS = 'ACTION_LEAVE_SUCCESS';
export const ACTION_LEAVE_FAIL = 'ACTION_LEAVE_FAIL';
export const ACTION_LEAVE_ERROR = 'ACTION_LEAVE_ERROR';
// get days between leaves

export const ACTION_DAYS_BETWEEN_LEAVES_SUCCESS = 'ACTION_DAYS_BETWEEN_LEAVES_SUCCESS';
export const ACTION_DAYS_BETWEEN_LEAVES_FAIL = 'ACTION_DAYS_BETWEEN_LEAVES_FAIL';
export const ACTION_DAYS_BETWEEN_LEAVES_ERROR = 'ACTION_DAYS_BETWEEN_LEAVES_ERROR';

// LIST LEAVES
export const ACTION_LIST_LEAVES_SUCCESS = 'ACTION_LIST_LEAVES_SUCCESS';
export const ACTION_LIST_LEAVES_EMPTY = 'ACTION_LIST_LEAVES_EMPTY';
export const ACTION_LIST_LEAVES_ERROR = 'ACTION_LIST_LEAVES_ERROR';

// Filter leaves
export const ACTION_SELECT_LEAVE = 'ACTION_SELECT_LEAVE';
export const ACTION_LEAVE_FILTER = 'ACTION_LEAVE_FILTER';

// MANAGE LEAVES
export const ACTION_LEAVE_STATUS_CHANGE_SUCCESS = 'ACTION_LEAVE_STATUS_CHANGE_SUCCESS';
export const ACTION_LEAVE_STATUS_CHANGE_FAIL = 'ACTION_LEAVE_STATUS_CHANGE_FAIL';
export const ACTION_LEAVE_STATUS_CHANGE_ERROR = 'ACTION_LEAVE_STATUS_CHANGE_ERROR';
// my leaves

export const ACTION_LIST_MY_LEAVES_SUCCESS = 'ACTION_LIST_MY_LEAVES_SUCCESS';
export const ACTION_LIST_MY_LEAVES_EMPTY = 'ACTION_LIST_MY_LEAVES_EMPTY';
export const ACTION_LIST_MY_LEAVES_ERROR = 'ACTION_LIST_MY_LEAVES_ERROR';

// export const ACTION_LOGIN_ERROR = "ACTION_LOGIN_ERROR"

// +++SALARY+++

export const ACTION_SUCCESS_SALARY_DETAILS = 'ACTION_SUCCESS_SALARY_DETAILS';
export const ACTION_EMPTY_SALARY_DETAILS = 'ACTION_EMPTY_SALARY_DETAILS';
export const ACTION_ERROR_USER_SALARY_DETAILS = 'ACTION_ERROR_USER_SALARY_DETAILS';

// +++USER+++

// attendence SUMMARY
export const ACTION_SUCCESS_ATTENDANCE_SUMMARY = 'ACTION_SUCCESS_ATTENDANCE_SUMMARY';
export const ACTION_EMPTY_ATTENDANCE_SUMMARY = 'ACTION_EMPTY_ATTENDANCE_SUMMARY';
export const ACTION_ERROR_ATTENDANCE_SUMMARY = 'ACTION_ERROR_ATTENDANCE_SUMMARY';

// my document
export const ACTION_SUCCESS_MY_DOCUMENT = 'ACTION_SUCCESS_MY_DOCUMENT';
export const ACTION_ERROR_MY_DOCUMENT = 'ACTION_ERROR_MY_DOCUMENT';
// my profile
export const ACTION_SUCCESS_MY_PROFILE = 'ACTION_SUCCESS_MY_PROFILE';
export const ACTION_EMPTY_MY_PROFILE = 'ACTION_EMPTY_MY_PROFILE';
export const ACTION_ERROR_MY_PROFILE = 'ACTION_ERROR_MY_PROFILE';
// update profile details
export const ACTION_SUCCESS_UPDATE_PROFILE_DETAILS = 'ACTION_SUCCESS_UPDATE_PROFILE_DETAILS';
export const ACTION_ERROR_UPDATE_PROFILE_DETAILS = 'ACTION_ERROR_UPDATE_PROFILE_DETAILS';
// update bank details
export const ACTION_SUCCESS_UPDATE_BANK_DETAILS = 'ACTION_SUCCESS_UPDATE_BANK_DETAILS';
export const ACTION_ERROR_UPDATE_BANK_DETAILS = 'ACTION_ERROR_UPDATE_BANK_DETAILS';
// update password
export const ACTION_SUCCESS_UPDATE_PASSWORD = 'ACTION_SUCCESS_UPDATE_PASSWORD';
export const ACTION_ERROR_UPDATE_PASSWORD = 'ACTION_ERROR_UPDATE_PASSWORD';
