import {urls, user, month, year, contains, click, wait, shouldNotBeVisble, shouldBeVisible} from '../../../index';
import {signin, signout, apiCall} from '../../../helper';
import {urlVisited, visitIndexRoute} from '../../../visitRoutes';

describe('Test leaves page', () => {
  it('api is fired to get leaves and will list under the 4 tabs', () => {
    signin(user.admin);
    urlVisited(urls.baseUrl + urls.home);
    shouldBeVisible('.nav > #manage_leaves');
    click('.nav > #manage_leaves');
    shouldBeVisible('.nav-sub > #manage_leaves');
    click('.nav-sub > #manage_leaves');
    urlVisited(urls.baseUrl + urls.manageLeaves);
    shouldBeVisible('.app-body');
    shouldBeVisible('.app-body .padding');
    shouldBeVisible('.app-body .padding .row > div');
  });
  it('every tab will have list of employees falls under that tab in left panel', () => {
    signin(user.admin);
    urlVisited(urls.baseUrl + urls.home);
    shouldBeVisible('.nav > #manage_leaves');
    click('.nav > #manage_leaves');
    shouldBeVisible('.nav-sub > #manage_leaves');
    click('.nav-sub > #manage_leaves');
    urlVisited(urls.baseUrl + urls.manageLeaves);
    shouldBeVisible('.app-body');
    shouldBeVisible('.app-body .padding');
    shouldBeVisible('.app-body .padding .row > div');
    shouldBeVisible('#manage_leave_header');
    shouldBeVisible('#manage_leave_header .leaves-tab .blue');
    shouldBeVisible('#manage_leave_header .leaves-tab .yellow-A200');
    shouldBeVisible('#manage_leave_header .leaves-tab .green-A200');
    shouldBeVisible('#manage_leave_header .leaves-tab .red-500');
    click('#manage_leave_header .leaves-tab .blue');
    shouldBeVisible('#no_manage_leave');
    click('#manage_leave_header .leaves-tab .yellow-A200');
    shouldBeVisible('#manage_leave_data');
    click('#manage_leave_header .leaves-tab .green-A200');
    shouldBeVisible('#manage_leave_data');
    click('#manage_leave_header .leaves-tab .red-500');
    shouldBeVisible('#manage_leave_data');
  });
  it('clicking any user on left panel will show respective leave detail on right panel', () => {
    signin(user.admin);
    urlVisited(urls.baseUrl + urls.home);
    shouldBeVisible('.nav > #manage_leaves');
    click('.nav > #manage_leaves');
    shouldBeVisible('.nav-sub > #manage_leaves');
    click('.nav-sub > #manage_leaves');
    urlVisited(urls.baseUrl + urls.manageLeaves);
    shouldBeVisible('.app-body');
    shouldBeVisible('.app-body .padding');
    shouldBeVisible('.app-body .padding .row > div');
    shouldBeVisible('#manage_leave_header');
    shouldBeVisible('#manage_leave_header .leaves-tab .blue');
    shouldBeVisible('#manage_leave_header .leaves-tab .yellow-A200');
    shouldBeVisible('#manage_leave_header .leaves-tab .green-A200');
    shouldBeVisible('#manage_leave_header .leaves-tab .red-500');
    click('#manage_leave_header .leaves-tab .yellow-A200');
    shouldBeVisible('#manage_leave_data');
    shouldBeVisible('#leavesList');
    shouldBeVisible('#leaveList0');
    click('#leaveList0');
    shouldBeVisible('#leaveDetails');
  });
});
